package ru.nikita.snakegame.utils

const val KEY_SETTINGS = "SETTINGS"

const val KEY_SETTINGS_SNAKE_COLOR = "SNAKE_COLOR"
const val KEY_SETTINGS_SNAKE_SPEED = "SNAKE_SPEED"
const val KEY_SETTINGS_SNAKE_LEVEL = "SNAKE_LEVEL"
const val KEY_SETTINGS_SNAKE_ORIENTATION = "SNAKE_ORIENTATION"
const val KEY_SETTINGS_SNAKE_LANGUAGE = "SNAKE_LANGUAGE"
const val KEY_SETTINGS_SNAKE_THEME = "SNAKE_THEME"

const val KEY_SCREEN_WIDTH = "KEY_SCREEN_WIDTH"
const val KEY_SCREEN_HEIGHT = "KEY_SCREEN_HEIGHT"

const val KEY_SCREEN_COEFFICIENT = "KEY_SCREEN_COEFFICIENT"

const val KEY_HIGH_SCORE = "KEY_HIGH_SCORE"