package ru.nikita.snakegame.utils

const val KEY_SETTINGS = "SETTINGS"

const val KEY_SETTINGS_SNAKE_COLOR = "SNAKE_COLOR"
const val KEY_SETTINGS_SNAKE_SPEED = "SNAKE_SPEED"
const val KEY_SETTINGS_SNAKE_LEVEL = "SNAKE_LEVEL"
const val KEY_SETTINGS_SNAKE_ORIENTATION = "SNAKE_ORIENTATION"
const val KEY_SETTINGS_SNAKE_LANGUAGE = "SNAKE_LANGUAGE"
const val KEY_SETTINGS_SNAKE_THEME = "SNAKE_THEME"